### ISSUE TITLE
OpenCV Error - persistence.cpp - cvGetFileNodeByName

### ISSUE THREAD

**Issue by weiweikong** [alejocb/dpptam#5]
@alejocb @amiltonwong 
After successfully catkin_make the package, I run
```
rosrun dpptam dpptam
```
then, got
```
OpenCV Error: Bad argument (Invalid pointer to file storage) in cvGetFileNodeByName, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/persistence.cpp, line 740
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/persistence.cpp:740: error: (-5) Invalid pointer to file storage in function cvGetFileNodeByName
```

I tried to uncomment 
```
chdir("/home/alejo/catkin_ws");
```
and changed it to my path, but it was still failed to run.

**Comment by amiltonwong** [comment]
@weiweikong ,
It seems the issue from opencv-2.4.8, which points to /build/buildd/opencv-2.4.8+dfsg1
I guess you had installed another standalone opencv-2.4.8 (besides ros)  in your system.  
How about remove that opencv linking and use the one provided by ROS?

**Comment by weiweikong** [comment]
@amiltonwong ，I removed OpenCV with synaptic while this progress also delete some ROS packages. So I reinstall ROS indigo and `ros-indigo-vision-opencv` package. However, it seems that the 2.4.8 version of OpenCV was default installed when I setup ROS indigo environment.

```
The following extra packages will be installed:

  gazebo2 libcv-dev libcvaux-dev libhighgui-dev libopencv-calib3d-dev

  libopencv-calib3d2.4 libopencv-contrib-dev libopencv-contrib2.4

  libopencv-core-dev libopencv-core2.4 libopencv-dev libopencv-features2d-dev

  libopencv-features2d2.4 libopencv-flann-dev libopencv-flann2.4

  libopencv-gpu-dev libopencv-gpu2.4 libopencv-highgui-dev

  libopencv-highgui2.4 libopencv-imgproc-dev libopencv-imgproc2.4

  libopencv-legacy-dev libopencv-legacy2.4 libopencv-ml-dev libopencv-ml2.4

  libopencv-objdetect-dev libopencv-objdetect2.4 libopencv-ocl-dev

  libopencv-ocl2.4 libopencv-photo-dev libopencv-photo2.4

  libopencv-stitching-dev libopencv-stitching2.4 libopencv-superres-dev

  libopencv-superres2.4 libopencv-ts-dev libopencv-ts2.4 libopencv-video-dev

  libopencv-video2.4 libopencv-videostab-dev libopencv-videostab2.4

  libopencv2.4-java libopencv2.4-jni libplayerdrivers3.0 opencv-data

  python-opencv robot-player ros-indigo-camera-calibration

  ros-indigo-compressed-depth-image-transport

  ros-indigo-compressed-image-transport ros-indigo-cv-bridge

  ros-indigo-depth-image-proc ros-indigo-desktop ros-indigo-gazebo-plugins

  ros-indigo-gazebo-ros ros-indigo-gazebo-ros-pkgs ros-indigo-image-geometry

  ros-indigo-image-pipeline ros-indigo-image-proc ros-indigo-image-rotate

  ros-indigo-image-transport-plugins ros-indigo-image-view

  ros-indigo-librviz-tutorial ros-indigo-perception

  ros-indigo-rqt-common-plugins ros-indigo-rqt-image-view

  ros-indigo-rqt-robot-plugins ros-indigo-rqt-rviz ros-indigo-rviz

  ros-indigo-rviz-plugin-tutorials ros-indigo-rviz-python-tutorial

  ros-indigo-simulators ros-indigo-stereo-image-proc

  ros-indigo-theora-image-transport ros-indigo-urdf-tutorial

  ros-indigo-vision-opencv ros-indigo-visualization-tutorials ros-indigo-viz
```

**Comment by weiweikong** [comment]
@amiltonwong Thank you for your reply! It was solved by completely removing OpenCV 2.4.8 and reinstall ROS indigo as usual.

**Comment by amiltonwong** [comment]
Great!

**Comment by TengFeiHan0** [comment]
@weiweikong could you tell me the detailed steps about removing OpenCV and reinstall ROS indigo? I have tried it but didn't solve the problem.
